version: '3.8'

services:
  fastapi:
    build:
      context: ./service-api
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./service-api/model.pth:/app/model.pth:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - prom

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - prom

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yaml
      - ./service-api:/app
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    networks:
      - prom

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=nickclonemail1@gmail.com
      - GF_SMTP_PASSWORD=wsgj hmze dnzx jmqo
      - GF_SMTP_FROM_ADDRESS=nickclonemail1@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
      - GF_SMTP_SKIP_VERIFY=true
    restart: unless-stopped
    networks:
      - prom

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus-3.4.1.linux-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus-3.4.1.linux-amd64/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - prom

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - prom

volumes:
  grafana-storage:

networks:
  prom:
