global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'gpu'
    static_configs:
      - targets: ['host.docker.internal:9400']
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - 'alertmanager:9093'