global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'youremail@gmail.com'
  smtp_auth_username: 'youremail@gmail.com'
  smtp_auth_password: 'your_password'
route:
  receiver: 'email-notifications'
  routes:
    - receiver: 'retrain-webhook'
      match:
        alertname: LowConfidenceScore

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'youremail_recv@gmail.com'
        send_resolved: true
  - name: 'retrain-webhook'
    webhook_configs:
    - url: 'http://localhost:8080/retrain'
      send_resolved: false
